version: "2.1"

services:
  # ====================================================
  #                    SAURON-BOT
  # ====================================================
  sauron-bot:
    image: ghcr.io/notchum/sauron-bot:main
    container_name: sauron-bot
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - TZ=America/New_York
    volumes:
      - /tmp:/tmp
    restart: unless-stopped
  # ====================================================
  #                     POSTGRESQL
  # ====================================================
  postgresql:
    image: notchum/postgres-spgist-bktree:16
    container_name: sauron-postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - TZ=America/New_York
    # Wait for postgres to be accept connections before starting the bot.
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "postgres"
        ]
      start_period: 40s
      start_interval: 1s
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-data-init-scripts:/docker-entrypoint-initdb.d/
    restart: unless-stopped
