name: Bug Report
description: Report broken or incorrect behaviour
title: "[BUG]"
labels: bug
assignees: ''
body:
  - type: input
    attributes:
      label: Summary
      description: A simple summary of your bug report
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: >
         What you did to make it happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Results
      description: >
        What did you expect to happen?
    validations:
      required: true
  - type: input
    attributes:
      label: Actual Results
      description: >
        What actually happened? Include any logs or screenshots here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: If you have an idea of a suitable solution, please explain here.
  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.
